### ISSUE TITLE
Start snap "keystone" (154) services ([start snap.keystone.nginx.service] failed with exit status 1

### ISSUE THREAD

**Issue by Haomeng** [openstack-snaps/snap-test#1] opened 2017-08-29 00:07 UTC
+ sudo snap install --channel=ocata/edge keystone
error: cannot perform the following tasks:
- Start snap "keystone" (154) services ([start snap.keystone.nginx.service] failed with exit status 1: Job for snap.keystone.nginx.service failed because a fatal signal was delivered to the control process. See "systemctl status snap.keystone.nginx.service" and "journalctl -xe" for details.
)
#systemctl status snap.keystone.nginx.service
● snap.keystone.nginx.service
   Loaded: not-found (Reason: No such file or directory)
   Active: activating (start) (Result: exit-code) since Tue 2017-08-29 00:04:24 UTC; 1min 2s ago

Aug 29 00:04:25 test-deploy-mgr snap[25227]:   File "/snap/keystone/154/lib/python2.7/site-packages/eventlet/greenio/__init__.py", line 6, in <module>
Aug 29 00:04:25 test-deploy-mgr snap[25227]: ImportError: No module named py2
Aug 29 00:04:25 test-deploy-mgr snap[25227]: Traceback (most recent call last):
Aug 29 00:04:25 test-deploy-mgr snap[25227]:   File "/snap/keystone/154/bin/snap-openstack", line 7, in <module>
Aug 29 00:04:25 test-deploy-mgr snap[25227]:   File "/snap/keystone/154/lib/python2.7/site-packages/snap_openstack/cmd/run.py", line 21, in <module>
Aug 29 00:04:25 test-deploy-mgr snap[25227]:   File "/snap/keystone/154/lib/python2.7/site-packages/snap_openstack/base.py", line 21, in <module>
Aug 29 00:04:25 test-deploy-mgr snap[25227]:   File "/snap/keystone/154/lib/python2.7/site-packages/oslo_concurrency/lockutils.py", line 27, in <module>
Aug 29 00:04:25 test-deploy-mgr snap[25227]:   File "/snap/keystone/154/lib/python2.7/site-packages/fasteners/__init__.py", line 29, in <module>
Aug 29 00:04:25 test-deploy-mgr snap[25227]: ImportError: No module named process_lock
Aug 29 00:04:25 test-deploy-mgr systemd[1]: snap.keystone.nginx.service: Control process exited, code=exited status=1

**Comment by Haomeng** [comment] 2017-08-29 00:08
I just run  "sudo ./snap-deploy" to deploy openstack, any ideas?

**Comment by coreycb** [comment] 2017-08-29 12:50
Hi Haomeng,

Thanks for reporting this. What version of Ubuntu are you running on?

Corey

**Comment by coreycb** [comment] 2017-08-29 13:19
Haomeng, I just ran snap-deploy on a new xenial instance without any issues. Is there any chance that you've rebuilt the keystone snap?

**Comment by Haomeng** [comment] 2017-08-30 01:40
Hi Coreycb,

My ubuntu is 16.04, code name is xenial, but it is a vm, so the system image is cloud image, I will try with ubuntu 16.04 xenial iso dvd installation distribution again. Any OS requirements for the snap deploy utils?

I did a try with ubuntu 17.04 ISO distribution, snap-deploy can run without any issue, but nova hypervisor-list show empty list, and can not boot vm without any hypervisor. Just assume we dont support the latest version 17.04, right?


Thanks
Haomeng

**Comment by Haomeng** [comment] 2017-08-30 01:47
Hi Coreycb,

I did not rebuilt the keystone snap.

Thanks
Haomeng

**Comment by coreycb** [comment] 2017-08-30 17:43
I'm also running on a 16.04 VM, well an instance on OpenStack using a cloud image. 

The only additional setup I perform on the instance is:
apt install git
snap install core
git clone https://github.com/openstack-snaps/snap-test.git

**Comment by coreycb** [comment] 2017-08-30 17:52
That is odd. Here's what I see when I install the snap:
```
ubuntu@x1:~$ sudo snap install --channel=ocata/edge keystone
keystone (ocata/edge) ocata from 'james-page' installed
ubuntu@x1:~$ ls /snap/keystone/154/lib/python2.7/site-packages/eventlet/greenio/
base.py  __init__.py  py2.py  py3.py
```

**Comment by coreycb** [comment] 2017-08-30 17:57
As for nova-hypervisor on 17.04, that's a known issue. Currently we have to install nova-hypervisor on 16.04 because that is what the published snap is built on. Otherwise you may hit [1] (nova-compute.log). Building nova-hypervisor on xenial and installing on xenial works fine. The reason for this is that upstream nova code detects libvirt features based on the version of libvirt on the machine it was built on.

[1] http://paste.ubuntu.com/24963944/

**Comment by coreycb** [comment] 2017-08-30 18:01
Can you try the following:  snap install --devmode --channel=ocata/edge keystone
If this is successful, the issue is likely a seccomp or AppArmor policy issue.

Also it's possible that the traceback you originally pasted is just a side-effect later on after the original failure. Can you attach more from /var/log/syslog at the time of failure?

**Comment by Haomeng** [comment] 2017-09-02 01:36
Thanks for your helping, New findings, I did some test and found that is not work with Ubuntu **16.04.1** LTS, but it is work as well with Ubuntu **16.04.3** LTS, that is odd to say what difference to make the failure openstack-snap behavior.

**Comment by coreycb** [comment] 2017-09-12 21:05
You may have been hitting libvirt policy violations. If you look at the git log for snap-test you'll notice the following commit:

commit a368cbf4890fe9a3f6e8b57c251fe75f6f2a26ed (HEAD -> master, origin/master, origin/HEAD)
Author: Corey Bryant <corey.bryant@canonical.com>
Date:   Wed Aug 9 19:49:44 2017 +0000

    Run with virt-aa-helper in enforcing mode
    
    Libvirt has been fixed [0] to enable running the nova-hypervisor
    snap with virt-aa-helper in enforcing mode.
    
    [0] https://bugs.launchpad.net/ubuntu/+bug/1644507

You may have been running with the new version of snap-test (with virt-aa-helper in enforcing mode) and an old version of xenial that didn't have the fix for https://bugs.launchpad.net/ubuntu/+bug/1644507.

If this were the case you would notice AppArmor denials in system logs, in particular when accessing the following:
  /var/snap/nova-hypervisor/common/instances/_base/
  /var/snap/nova-hypervisor/common/instances/snapshots/

**Comment by coreycb** [comment] 2017-10-03 20:15
Closing this issue as it's been resolved.

**Closed as completed by coreycb** 2017-10-03 20:15 UTC
